const fs = require("fs");
const YAML = require("yaml");

let stages = ["live", "test"];

stages.forEach((stage) => {
  let index = {};
  let folders = ["articles", "presentations", "projects"];

  folders.forEach((folder) => {
    index[folder] = [];
    fs.readdirSync(`./content/${stage}/${folder}`).forEach((file) => {
      if (file.endsWith(".md")) {
        const data = fs.readFileSync(
          `./content/${stage}/${folder}/${file}`,
          "utf8"
        );
        let yamlEnd = data.lastIndexOf("\n---\n");
        if (yamlEnd > 0) {
          let yaml = data.substring(4, yamlEnd);
          let item = YAML.parse(yaml);
          item.file = `/content/${stage}/${folder}/${file}`;
          item.url = `/${folder}/${file.substring(0, file.length - 3)}`;
          index[folder].push(item);
        }
      }
    });
  });

  index.about = [
    {
      title: "About",
      url: "/about",
      file: `/content/${stage}/about.md`,
      noBackButton: true,
    },
  ];

  // Emit index.js
  let data =
    "// This index was automatically generated by a tool. Do not edit.\n";
  data += `export const ${stage}index = ${JSON.stringify(index)}`;
  fs.writeFileSync(`./content/${stage}/index.js`, data);
  console.log(`Content generated for ${stage}`);
});
