name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: AWS Deployment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Pandoc
        uses: docker://pandoc/core:2.18
      - run: npm install
      - run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CERTIFICATE_ID: ${{ secrets.CERTIFICATE_ID }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}